

import time

import chromedriver_autoinstaller
from selenium import webdriver
from selenium.webdriver import Keys
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=Service(chromedriver_autoinstaller.install()))
driver.get("https://yef-test.cormsquare.com/Identity/Account/Login")
driver.maximize_window()
time.sleep(2)


class test_YEF:
   def test_login_YEF(self):
        driver.implicitly_wait(10)
        username=driver.find_element(By.XPATH,'//input[@name="Input.Email"]')
        webdriver.ActionChains(driver).send_keys_to_element(username, 'requester@cormsquare.com').perform()
        password = driver.find_element(By.XPATH, '//input[@name="Input.Password"]')
        webdriver.ActionChains(driver).send_keys_to_element(password, 'Admin@123').perform()
        login = driver.find_element(By.XPATH, '//button[@id="login-submit"]').click()

        create = driver.find_element(By.XPATH, '//*[@id="content"]/div[1]/div[2]/div/div[2]/button').click()
        time.sleep(2)
        POC_NC = driver.find_element(By.XPATH, '//a[@href="/Procurement/Requisitions/POC_NonCatalog_Create"]').click()
        time.sleep(2)

        title=driver.find_element(By.XPATH,'//*[@id="title"]')
        webdriver.ActionChains(driver).send_keys_to_element(title,'NC-Test flow-001').perform()
        time.sleep(2)
        ProjectDD=driver.find_element(By.XPATH,"//span[text()='-- Select Project --']").click()
        Projectfield=driver.find_element(By.XPATH,"//input[@class='select2-search__field']")
        webdriver.ActionChains(driver).send_keys_to_element(Projectfield,Keys.ENTER, 'E143').perform()
        driver.find_element(By.XPATH,'//ul//li[@class="select2-results__option select2-results__option--highlighted"]').click()
        time.sleep(4)
        WBSDD=driver.find_element(By.XPATH,'//span[text()="-- Select WBS --"]').click()
        WBSVal=driver.find_element(By.XPATH,'//input[@class="select2-search__field"]')
        webdriver.ActionChains(driver).send_keys_to_element(WBSVal,Keys.ARROW_DOWN,Keys.ENTER).perform()
        time.sleep(2)
        IntercomDD=driver.find_element(By.XPATH,'//span[text()="-- Select Incoterm --"]').click()
        IntercomVal=driver.find_element(By.XPATH,'//input[@class="select2-search__field"]')
        webdriver.ActionChains(driver).send_keys_to_element(IntercomVal, ' ').perform()
        driver.find_element(By.XPATH,'//li[@class="select2-results__option select2-results__option--highlighted"]').click()
        time.sleep(2)
        LD_DD=driver.find_element(By.XPATH,'//span[text()="-- Select Liquidated Damages --"]').click()
        LD_val=driver.find_element(By.XPATH,'//input[@class="select2-search__field"]')
        webdriver.ActionChains(driver).send_keys_to_element(LD_val, ' ').perform()
        driver.find_element(By.XPATH,'//li[@class="select2-results__option select2-results__option--highlighted"]').click()
        time.sleep(2)
        PriceVal_DD=driver.find_element(By.XPATH,'//span[text()="-- Select Price Validity --"]').click()
        PriceVal_val=driver.find_element(By.XPATH,'//input[@class="select2-search__field"]')
        webdriver.ActionChains(driver).send_keys_to_element(PriceVal_val, ' ').perform()
        driver.find_element(By.XPATH,'//li[@class="select2-results__option select2-results__option--highlighted"]').click()
        time.sleep(2)
        driver.execute_script("window.scrollBy(0, 400);")
        ShippingAdd_DD=driver.find_element(By.XPATH,'//*[@id="select2-endusersId-container"]').click()
        ShippingAdd_val=driver.find_element(By.XPATH,'//input[@class="select2-search__field"]')
        webdriver.ActionChains(driver).send_keys_to_element(ShippingAdd_val, ' ').perform()
        driver.find_element(By.XPATH,'//li[@class="select2-results__option select2-results__option--highlighted"]').click()
        time.sleep(2)
        ShippingMode_dd=driver.find_element(By.XPATH, '//span[text()="-- Select Shipping Mode --"]')
        webdriver.ActionChains(driver).send_keys_to_element(ShippingMode_dd, ' ').perform()
        driver.find_element(By.XPATH,'//li[@class="select2-results__option select2-results__option--highlighted"]').click()
        time.sleep(2)
        Quotation=driver.find_element(By.XPATH,'//*[@id="dates"]/div[1]/input[2]').click()
        driver.find_element(By.XPATH,'/html/body/div[4]/div[2]/div/div[2]/div/span[32]').click()
        time.sleep(2)
        Expected_PO_issue=driver.find_element(By.XPATH,'//*[@id="dates"]/div[2]/input[2]').click()
        driver.find_element(By.XPATH,'/html/body/div[5]/div[2]/div/div[2]/div/span[33]').click()
        time.sleep(2)
        Expected_delivery=driver.find_element(By.XPATH,'//*[@id="dates"]/div[3]/input[2]').click()
        driver.find_element(By.XPATH,'/html/body/div[6]/div[2]/div/div[2]/div/span[34]').click()
        time.sleep(2)
        OrderIntake=driver.find_element(By.XPATH,'//*[@id="orderintakeid"]').send_keys('9999')
        time.sleep(2)
        TargetPrice=driver.find_element(By.XPATH,'//*[@id="targetpriceid"]').send_keys('8000')
        time.sleep(2)
        checker=driver.find_element(By.XPATH,'//span[text()="-- Select Checker --"]').click()
        driver.find_element(By.XPATH,'//input[@class="select2-search__field"]').send_keys('checker')
        driver.find_element(By.XPATH,'//li[text()="checker@cormsquare.com"]').click()
        time.sleep(2)

        driver.execute_script("window.scrollBy(0, 650);")
        time.sleep(2)
        InLineReq=driver.find_element(By.XPATH,'//*[@id="addLineRequisitionItems"]').click()
        time.sleep(2)
        Categories=driver.find_element(By.XPATH,'//span[text()="-- Select Categories --"]').click()
        driver.find_element(By.XPATH,'//input[@class="select2-search__field"]').send_keys('Analyzer',Keys.ENTER)
        time.sleep(2)
        Item=driver.find_element(By.XPATH,'//span[text()="-- Select Item --"]').click()
        driver.find_element(By.XPATH, '//input[@class="select2-search__field"]').send_keys('Analyzer')
        driver.find_element(By.XPATH,'//li[text()="Dust Analyzer "]').click()
        time.sleep(2)
        Qty=driver.find_element(By.XPATH,'//input[@id="quantity"]').send_keys('15')
        time.sleep(2)
        Add=driver.find_element(By.XPATH,'//button[@id="saveRequisitionItem"]').click()
        time.sleep(2)
        driver.execute_script("window.scrollBy(0, 1000);")
        time.sleep(2)

        # Attachements=driver.find_element(By.XPATH,'//*[@id="attachDocs"]').click()
        # # time.sleep(5)
        # ChooseFile=driver.find_element(By.XPATH,'//*[@id="formFilePreupload"]').send_keys('C:\\Users\\CormSquare\\Documents\\Book1.xlsx')
        # # time.sleep(2)
        #
        # AttachFile=driver.find_element(By.XPATH,'//*[@id="saveAttachments1"]').click()
        # # time.sleep(2)
        # ChooseFile = driver.find_element(By.XPATH, '//*[@id="formFilePreupload"]').send_keys('C:\\Users\\CormSquare\\Documents\\Book1.xlsx')
        # # time.sleep(2)
        # External=driver.find_element(By.XPATH,'//input[@id="radioInActive" or value="External"]').click()
        # AttachFile = driver.find_element(By.XPATH, '//*[@id="saveAttachments1"]').click()
        # time.sleep(2)
        # Continue=driver.find_element(By.XPATH,'//*[@id="modalAttachments"]//button[text()="Continue"]').click()
        # time.sleep(2)

        # CreateDraft=driver.find_element(By.XPATH,'//button[@id="btnCreate"]').click()
        # time.sleep(2)
        driver.quit()
iobj=test_YEF()
test_YEF()
iobj.test_login_YEF()
